In [1]:
import numpy as np

In [9]:
#question 3
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
#question 4
print(np.ones((3,4)))
print(np.zeros((4,3)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
#question 5
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
np.matmul(A, B)

array([[ 6, 12, 18, 24],
       [15, 30, 45, 60]])

In [20]:
#question 6
mat = np.array([[3,1],[1,2]])
eigenvalues, eigenvectors = np.linalg.eig(mat)
print("Eigenvalues: ")
print(eigenvalues)
print("Eigenvectors: ")
print(eigenvectors)

Eigenvalues: 
[3.61803399 1.38196601]
Eigenvectors: 
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
